In [1]:
import jax
from jax import device_get, device_put, random
import jax.numpy as np

import numpy as onp

# Generate Multivariate Normal Data

In [17]:
d = 3
n = 10
r = 0.5

key = random.PRNGKey(0)

In [30]:
mu = np.zeros((d,))
mu

DeviceArray([0., 0., 0.], dtype=float32)

In [27]:
rho = onp.full((d, d), r)
rho[onp.diag_indices_from(rho)] = 1.0
rho = device_put(rho)
rho

DeviceArray([[1. , 0.5, 0.5],
             [0.5, 1. , 0.5],
             [0.5, 0.5, 1. ]], dtype=float32)

In [28]:
z = random.multivariate_normal(key, mu, rho, (n,))
z

DeviceArray([[-0.28371075,  0.6694512 , -0.692005  ],
             [ 1.4165013 ,  1.6213272 ,  1.756285  ],
             [-0.42656714,  0.6407802 , -0.383819  ],
             [ 0.01532494, -1.7924309 , -0.13934608],
             [ 0.9142364 ,  0.95461476,  1.2131029 ],
             [ 0.12106168, -0.21983227,  1.2926582 ],
             [ 0.24500382, -1.0734603 , -0.77513266],
             [ 0.14037243,  0.79851717, -0.58057636],
             [-1.0775021 , -1.5257134 , -1.352197  ],
             [-0.15576522, -0.40975612, -1.098453  ]], dtype=float32)

In [29]:
jax.scipy.stats.norm.cdf(z)

DeviceArray([[0.38831604, 0.74839616, 0.24446711],
             [0.9216856 , 0.9475262 , 0.9604801 ],
             [0.33484733, 0.7391672 , 0.3505563 ],
             [0.5061135 , 0.036532  , 0.44458833],
             [0.81970364, 0.8301137 , 0.88745475],
             [0.5481789 , 0.41300088, 0.90193534],
             [0.59677327, 0.14153232, 0.21913067],
             [0.5558171 , 0.7877147 , 0.28076303],
             [0.14062801, 0.06354064, 0.08815616],
             [0.43810904, 0.34099242, 0.1360034 ]], dtype=float32)

Basic algorithm

```
Let R be a d x d correlation matrix
Generate Z := MVN(0, R)
Compute  U := NormalCDF(Z)
```