In [1]:
import jax
import jax.numpy as np
import numpy as onp

import csv

In [2]:
rho = onp.loadtxt("brca_rho.tab", delimiter="\t")
rho[0:10, 0:10]

array([[ 1.        , -0.01301598,  0.14123724, -0.10308511, -0.26204787,
        -0.08292474,  0.64547595,  0.16234743, -0.15385011,  0.4721754 ],
       [-0.01301598,  1.        , -0.24707931,  0.02770884,  0.25542452,
         0.26156863, -0.052855  , -0.37699734, -0.09271484, -0.04467161],
       [ 0.14123724, -0.24707931,  1.        ,  0.26957427, -0.20179411,
        -0.32947896,  0.15704886, -0.00476229, -0.04586942,  0.05997399],
       [-0.10308511,  0.02770884,  0.26957427,  1.        , -0.06544319,
        -0.05847775, -0.0443766 , -0.15504393, -0.02538405, -0.03200717],
       [-0.26204787,  0.25542452, -0.20179411, -0.06544319,  1.        ,
         0.36626381, -0.24566953, -0.23739906,  0.00651204, -0.14096476],
       [-0.08292474,  0.26156863, -0.32947896, -0.05847775,  0.36626381,
         1.        , -0.068004  , -0.23439481, -0.05177342, -0.07236493],
       [ 0.64547595, -0.052855  ,  0.15704886, -0.0443766 , -0.24566953,
        -0.068004  ,  1.        ,  0.30655046

In [3]:
d = rho.shape[1]
n = 1212

In [4]:
mu = onp.zeros((d,))
mu

array([0., 0., 0., ..., 0., 0., 0.])

In [8]:
rho_chol = onp.linalg.cholesky(rho)

In [55]:
rho_d = jax.device_put(rho)
mu_d  = jax.device_put(mu)


In [56]:
key = jax.random.PRNGKey(0)

In [57]:
x_d = jax.random.multivariate_normal(key, mu_d, rho_d, (n,))

In [58]:
x_d.round(2)

DeviceArray([[nan, nan, nan, ..., nan, nan, nan],
             [nan, nan, nan, ..., nan, nan, nan],
             [nan, nan, nan, ..., nan, nan, nan],
             ...,
             [nan, nan, nan, ..., nan, nan, nan],
             [nan, nan, nan, ..., nan, nan, nan],
             [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)

In [50]:
x = jax.device_get(x_d)
x.round(2)

array([[-0.01,  0.46, -0.76, ..., -0.41, -0.3 , -0.39],
       [-0.36,  1.32,  0.71, ..., -0.2 , -1.79,  0.96],
       [-1.02,  0.45, -0.58, ...,  1.54,  1.16, -2.25],
       ...,
       [ 0.51, -1.04,  0.  , ..., -2.22, -1.3 ,  1.54],
       [ 1.8 , -0.41,  1.41, ..., -0.67, -0.9 ,  0.99],
       [-0.05,  0.1 , -0.1 , ..., -0.33, -0.02,  0.55]], dtype=float32)